alter table public.stores add column if not exists fantasy_name text;
alter table public.stores add column if not exists document text;
alter table public.stores add column if not exists responsible_name text;
alter table public.stores add column if not exists email text;
alter table public.stores add column if not exists whatsapp text;
alter table public.stores add column if not exists landline text;
alter table public.stores add column if not exists address_number text;
alter table public.stores add column if not exists complement text;
alter table public.stores add column if not exists district text;
alter table public.stores add column if not exists zip_code text;
alter table public.stores add column if not exists latitude numeric(10,7);
alter table public.stores add column if not exists longitude numeric(10,7);
alter table public.stores add column if not exists location_received text;
alter table public.stores add column if not exists delivery_distribution text;
alter table public.stores add column if not exists fixed_couriers text[] not null default '{}';
alter table public.stores add column if not exists opening_hours jsonb not null default '{}'::jsonb;
alter table public.stores add column if not exists allow_manual_order boolean not null default true;
alter table public.stores add column if not exists require_pickup_confirmation boolean not null default true;
alter table public.stores add column if not exists rate_courier_after_delivery boolean not null default true;
alter table public.stores add column if not exists internal_notes text;
